### ISSUE TITLE
Flash preload triggers two requests for video

### ISSUE THREAD

**Issue by danieltwagner** [videojs/video-js-swf#130]
I recently upgraded video-js-swf from 4.4.5 to 4.5.0 and found that the player now starts preloading instantly if preload is set to "auto" (that's great), but also that during this preload it sends two requests to the server, one of which is subsequently cancelled.

Using video.js 4.8 it doesn't preload but only sends a single request when playing:
http://jsbin.com/nibeyusawu/1

Using video.js 4.10 it preloads but sends two requests:
http://jsbin.com/cukutoxode/1

I have attached a screenshot of my Chrome Developer Tools' Network tab below showing the issue:
![screen shot 2014-11-11 at 17 08 30](https://cloud.githubusercontent.com/assets/734118/5003662/992d8080-69c5-11e4-942c-dab90e995bab.png)

**Comment by norlin** [comment]
Is anything new about this bug?

**Comment by mmcc** [comment]
I seem to remember an issue similar to this in the core tracker, but I'm having trouble finding it. No, I don't think anyone's dug in yet and this one's pretty low priority for us (assuming it's still happening in the latest 5.0 RC). Would you be interested in digging in?
