### ISSUE TITLE
Possible content spoofing vulnerability

### ISSUE THREAD

**Issue by tariel** [videojs/video-js-swf#133]
Hello,

I've recently received a notification from our security team that video-js.swf contains content spoofing vulnerability that is exposed via poster parameter:

http://vjs.zencdn.net/4.10/video-js.swf?poster=http://www.notcot.com/images/2011/03/posters.jpg
http://vjs.zencdn.net/4.10/video-js.swf?poster=http://www.flash-test.net/relog.swf

Security team has concerns that some other third-party content, not originating from the same domain, can be loaded via the poster parameter, as well as .swf files.

Should this be fixed by adding a validation for the poster parameter? Or do you think it would be better to make our own build of video-js.swf that allows poster images only from specific domains? What is your view on this issue?

**Comment by aegarbutt** [comment]
This isn't simply content-spoofing; this amounts to XSS as an external SWF can be included. That SWF can include other script that is now executing in the origin hosting the video-js.swf.

**Comment by lox** [comment]
This would seem to be basically a show-stopping XSS?
