### ISSUE TITLE
Player background

### ISSUE THREAD

**Issue by campones** [videojs/video-js-swf#134]
on a live scenario using the flash fallback, the poster (or player background) load at the beginning. 

If no stream is active, because autoplay is activated (which is a common scenario for live streams), the autoplay trigger and make the background disappear.

I think the poster should stay on if no stream is active ,and only disappear when stream is loaded and starts

**Comment by mashuai** [comment]
I have the same problem, poster only available when use HTML5 video. when fall back to flash, it appear a blank screen, and it also don't have a loading icon.
