### ISSUE TITLE
XSS Vulnerability video-js.swf

### ISSUE THREAD

**Issue by giorgiomarzianidepaolis-was** [videojs/video-js-swf#142]
We detected an XSS vulnerability:

Please try this link using safari or firefox, be sure to replace http://www.domain.com/path/to/ with a running webserver: 
http://www.domain.com/path/to/video-js.swf?readyFunction=alert

**Comment by mmcc** [comment]
Thanks for letting us know! This is fixed in the most recent release, but in the future, please consider [contacting us directly](https://en.wikipedia.org/wiki/Responsible_disclosure) about security vulnerabilities so we can have a chance to fix it before going public.
