### ISSUE TITLE
Is there a way to control the speed of playback?

### ISSUE THREAD

**Issue by MCaveMan** [videojs/video-js-swf#146]
Hi guys,
  I want to add a featue of controlling the speed of video playback into the video-js-swf. And I fund a way but seems not play smoothly. Here is the pseudo-code:
```javascript
i =0;
setInterval(function(){
    i += 1;
    myVideo.seek(i);
}, 500);
```
this will seek the video every 500ms. 
Is there any other way to control the speed of playback?

**Comment by mmcc** [comment]
There's `playbackRate` available for the html5 tech, but no, unfortunately there's no way to control the speed of playback via the Video.js SWF.
