### ISSUE TITLE
No setting to adjust buffer time

### ISSUE THREAD

**Issue by coosnake** [videojs/video-js-swf#163]
Is there a chance this setting will be customizable later? I find it very useful to be able to adjust the playback delay. I would like to stream my RTMP source with the smallest delay possible and videojs is the best free player I found but unfortunately lacks this setting!

**Comment by jgmio** [comment]
https://github.com/videojs/video-js-swf/pull/222 has this. Support his pull request with a thumbs up and a comment.

Again thanks to @sea-kg : https://github.com/sea-kg
