### ISSUE TITLE
Playing broadcast rtmp flv webcam from the browser, 100x100

### ISSUE THREAD

**Issue by Dimitros-ptz** [videojs/video-js-swf#168]
I tested multiple flash-publisher for broadcast camera directly from a web page. The problem only occurs when playing on videojs.swf, other players no problem.

To repeat the problem is enough to take any swf-application for broadcast webcam from the browser. When you try to play rtmp/flv, videojs reduces the size to 100x100. If you expand the player window to full screen and back, the image becomes normal.

A similar problem: https://github.com/videojs/video-js-swf/issues/55#issuecomment-112340618

Advise, please, flash-application to broadcast webcam from browser page, which will to work steadily with videojs. Or modify the video.swf for stable operation with rtmp / flv

Sorry for bad English.

last test:
videojs 4.12.10
swf 4.7.1

**Comment by hui** [comment]
+1

swf 4.7.2
