### ISSUE TITLE
Problem with seeking and spinner

### ISSUE THREAD

**Issue by gangstaJS** [videojs/video-js-swf#174]
http://ex.ua/test_player/demo_flv.html Big flv files slow seeking and spinner do not hide. After full buffering player starts working OK

**Comment by ange007** [comment]
@gangstaJS In videoJS isn't present a pseudostreaming *( and on how many I he understood it is necessary here )*, wrote a patch already long ago: https://github.com/videojs/video-js-swf/pull/135, but didn't accept it yet. )

> В videoJS нет псевдостриминга *( а на сколько я понял именно он нужен здесь )*, писал патч уже очень давно: https://github.com/videojs/video-js-swf/pull/135 , но его пока не приняли.

**Comment by EyMaddis** [comment]
I also noticed this issue. For me it occurs when I change the src (not sure if this is necessary for the bug to occur) and use the flash player.
I found a workaround by doing something like this:

```js
player.setSrc({type:'video/flv', src: ...})
fixUglySeekingBug = true

// later

player.on('playing', function() {
  if(fixUglySeekingBug) {
    player.currentTime(player.currentTime())
   fixUglySeekingBug = false;
  }
});
```
