### ISSUE TITLE
loadedmetadata event only firing after play is clicked

### ISSUE THREAD

**Issue by heff** [videojs/video-js-swf#177]
I think I remember some changes around load events in the recent past. Does anyone know if anything might have changed around loadedmetadata, or if this is a pre-existing condition?

@dmlap or @bclwhitaker?

See videojs/video.js#2439

**Comment by bclwhitaker** [comment]
The preload attribute is only partially supported in the swf.  Setting it to `preload="metadata"` is equivalent to `preload="none"`.  If the preload attribute is changed to `preload="auto"` the loadedmetadata event will fire before play but you will also get the download hit.

**Comment by heff** [comment]
Thanks Lee!
