### ISSUE TITLE
pseudo in videojs flash fallback

### ISSUE THREAD

**Issue by mzinko** [videojs/video-js-swf#185]
is there any way to make pseudo work with video js flash fallback

this is what i am using now

> videojs.options.flash.swf = "http://example.com/video-js.swf";
><source src="http://example.com/video.mp4"
>type="video/mp4"/>

tried to use html5

>data-setup='{"techOrder": ["html5", "flash"]}'>

with html5 i can seek in video fast using flash fallback need to wait till video downloaded

**Comment by mmcc** [comment]
There's a pull request and related conversation on #135.
