### ISSUE TITLE
video-js-swf doesn't work with native MediaSource input?

### ISSUE THREAD

**Issue by norlin** [videojs/video-js-swf#189]
Hi,

I have posted an issue videojs/videojs-contrib-media-sources#49, but now it seems it's a swf bug.
As I see in code ( master/src/VideoJS.as#L360 ), swf handles only `blob:vjs-media-source/` URLs while native MediaSource URLs goes without `vjs-media-source` prefix.

As a result, browser tries to download such url instead of waiting for MediaSource data.
The example: http://jsbin.com/pepifanihe/3

**Comment by dmlap** [comment]
The SWF won't every be able to play MSE-compatible streams directly. Flash only supports byte-input in FLV format and has a lower-level interaction model in that mode. videojs-contrib-media-sources is our attempt to bridge that gap but it's a big API and I'm sure there are holes here and there. Closing this one but we can continue to discuss in videojs/videojs-contrib-media-sources#49.
