### ISSUE TITLE
Stop manually editing flex-config.xml!!

### ISSUE THREAD

**Issue by dmlap** [videojs/video-js-swf#191]
It should always be this:

``` xml
  <!-- Specifies the minimum player version that will run the compiled SWF. -->
   <target-player>10.3</target-player>

    <!-- Specifies the version of the compiled SWF -->
    <swf-version>12</swf-version>
```

You can find it at node_modules/flex-sdk/lib/flex_sdk/frameworks/flex-config.xml. Please fix me!

**Comment by gkatsev** [comment]
Fixed by 0b0ed92. Still requires manual editing, but at least it's documented in the README.
