### ISSUE TITLE
About MPEG-DASH support for flash player

### ISSUE THREAD

**Issue by yy8678** [videojs/video-js-swf#193]
Hi, have any idea support MPEG-DASH on flash player?

**Comment by gkatsev** [comment]
You should check out the dash.as player and this post as well http://blog.videojs.com/post/92536319027/dash-everywhere-ish-hack-project

We're not going to add in dash support to our swf project, though, someone could write a fallback to a dash player (like [contrib-dash](/videojs/videojs-contrib-dash)) that uses the same flash fallback mechanism that our [contrib-hls](/videojs/videojs-contrib-hls) project uses.

Hope that helps.
