### ISSUE TITLE
Bug with cursor hiding in SWF player

### ISSUE THREAD

**Issue by Tugzrida** [videojs/video-js-swf#195]
When viewing an FLV(which therefore uses the SWF player), the cursor is not hidden after a period of inactivity as happens when viewing an MP4. I haven't done much flash coding so I don't really have an idea of how to fix it however SO suggests that it's easier in the flash side rather than using HTML/CSS. [This page](http://help.adobe.com/en_US/AS2LCR/Flash_10.0/help.html?content=00001267.html) looks to be the right function but I wouldn't know how to implement it.

Example: https://tugzrida.github.io/video-js-cursor-bug/ ([view source](https://github.com/Tugzrida/tugzrida.github.io/blob/master/video-js-bug/index.html))

**Comment by gkatsev** [comment]
Thanks for the detailed report. That adobe page does have the correct method. We'd want to call `Mouse.hide()` and `Mouse.show()` at the appropriate time. And in fact, you can't fix this from the HTML/CSS side.
The thing that makes it not super simple is that we'd only want this to happen in fullscreen and only after some inactivity timeout which should be reset whenever the mouse is moved.

**Comment by misiek08** [comment]
On every mouse move you can reset timeout if user is in fullscreen, and if
he exits then clear timeout and just leave mouse visible.

2015-12-17 17:39 GMT+01:00 Gary Katsevman <notifications@github.com>:
