### ISSUE TITLE
node package flex-sdk have a wrong version

### ISSUE THREAD

**Issue by caomulaodao** [videojs/video-js-swf#197]
in package.json,devDependencies: "flex-sdk": "4.6.0-0",
version  of flex-sdk is terrible.
if you npm install,it is a wrong.
version should is a num.

**Comment by gkatsev** [comment]
`4.6.0-0` is a valid version for the `flex-sdk` package.
I'm not sure what you mean otherwise.

**Comment by zcoding** [comment]
node version: v6.2.0
npm version: 3.10.5
system version: OS X 10.11.5

Error:
```bash
npm ERR! No compatible version found: flex-sdk@4.6.0-0
npm ERR! Valid install targets:
npm ERR! 4.5.1-0, 4.5.0-0, 4.1.0-0, 4.0.0-0, 3.6.0-0, 3.5.0, 3.5.0-0, 3.4.1-0, 3.4.0-0, 3.3.0-0, 3.2.0-0, 3.1.0-0, 3.0.1-0, 3.0.0-6, 3.0.0-5, 3.0.0-4, 3.0.0-3, 3.0.0-2, 3.0.0-1, 3.0.0-0
```

**Comment by gkatsev** [comment]
Not sure what's happening but it's there:
```sh
$ npm dist-tag ls flex-sdk
latest: 4.6.0-0
```
And the flex-sdk package page on npmjs.com corroborates: https://www.npmjs.com/package/flex-sdk
