### ISSUE TITLE
Error `npm install`

### ISSUE THREAD

**Issue by JasterTDC** [videojs/video-js-swf#198]
Hi there,

I've tried to run the first step, and the prompt shows me an error like this 

npm ERR! Error: Attempt to unlock playerglobal-latest@^0.1.6, which hasn't been locked
npm ERR!     at unlock (/usr/share/npm/lib/utils/locker.js:44:11)
npm ERR!     at cb (/usr/share/npm/lib/cache/add-named.js:32:5)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:41:20
npm ERR!     at /usr/share/npm/lib/utils/locker.js:22:20
npm ERR!     at /usr/share/npm/node_modules/inflight/inflight.js:22:7
npm ERR!     at Array.forEach (native)
npm ERR!     at res (/usr/share/npm/node_modules/inflight/inflight.js:21:9)
npm ERR!     at /usr/lib/nodejs/once.js:17:15
npm ERR!     at afterMkdir (/usr/share/npm/lib/cache/get-stat.js:53:14)
npm ERR!     at /usr/lib/nodejs/mkdirp/index.js:46:53
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "playerglobal-latest"
npm ERR! cwd /home/ismael/projects/video-js-swf/node_modules/flex-sdk
npm ERR! node -v v4.2.2
npm ERR! npm -v 1.4.21
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ismael/projects/video-js-swf/node_modules/flex-sdk/npm-debug.log
npm ERR! not ok code 0
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! flex-sdk@4.6.0-0 preinstall: `npm install playerglobal-latest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the flex-sdk@4.6.0-0 preinstall script.
npm ERR! This is most likely a problem with the flex-sdk package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install playerglobal-latest
npm ERR! You can get their info via:
npm ERR!     npm owner ls flex-sdk
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/ismael/projects/video-js-swf
npm ERR! node -v v4.2.2
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ismael/projects/video-js-swf/npm-debug.log
npm ERR! not ok code 0

I'm using debian.

Ismael

**Comment by gkatsev** [comment]
npm 1.x is old. Please update to latest npm 2.x.
