### ISSUE TITLE
Setup Guide media URLs access denied

### ISSUE THREAD

**Issue by wiserweb** [videojs/video-js-swf#203]
On this page (http://docs.videojs.com/docs/guides/setup.html) the links to the video media are returning access denied. This might be affecting other parts of the documentation also but I have not investigated deeper. I simply used the URLs from videojs homepage which are valid.

`http://video-js.zencoder.com/oceans-clip.mp4`

 <source src="http://video-js.zencoder.com/oceans-clip.mp4" type="video/mp4" />
 <source src="http://video-js.zencoder.com/oceans-clip.webm" type="video/webm" />
 <source src="http://video-js.zencoder.com/oceans-clip.ogv" type="video/ogg" />

**Comment by gkatsev** [comment]
oh, right, we should probably update those urls. The new link is http://vjs.zencdn.net/v/oceans.mp4.
