### ISSUE TITLE
why can't play my rtmp video

### ISSUE THREAD

**Issue by sanyuelanv** [videojs/video-js-swf#206]
in my work ,i have to play the ramp video.
but i must to click the big-play-button and then click the small-play-button which in the controls bar to play my video ?

**Comment by mister-ben** [comment]
If you mean video.js's big play button, this sounds like a bug in the flash tech that was fixed a while back. Make sure you're using the latest version.

If you mean the play button on some browsers' click-to-play overlay on Flash content, that's out of video.js's control.

**Comment by sanyuelanv** [comment]
@mister-ben 
thx your answer.
i mean that i have to click the button which  in the controls bar to play the video.
i use js like **this.play()** have any help.

**Comment by gkatsev** [comment]
Unfortunately, we can't be of much help for questions like these without a reproducible (and preferably minimal) test-case.
Closing for now until/if we get more info.
