### ISSUE TITLE
Chrome going to block flash

### ISSUE THREAD

**Issue by sgavali** [videojs/video-js-swf#209]
https://www.yahoo.com/tech/google-chrome-soon-join-others-221819682.html

Will it affect VJS plugin ?

**Comment by BrandonOCasey** [comment]
it will probably have an effect all though what happens is still up in the air. 
* A blog post that was written by our team about this: http://blog.videojs.com/the-end-of-html-first/ 
* An issue that is open in video.js to talk about it: https://github.com/videojs/video.js/issues/3520

**Comment by gkatsev** [comment]
I wanted to add, it won't affect the swf directly. Google is going to prevent us from knowing whether flash is available in most cases, once this goes into effect, so, from videojs's prespective, the Flash tech will never be supported anymore.
However, they did say that if you did end up putting a swf into the page, the user would be greeted by the current puzzle piece icon to run the plugin if you want (similar to how it currently does if you tell chrome to only run plugins on demand). The website just will not be able to know ahead of time whether the user actually has Flash or whether the user just never let Flash run.
See https://chrome.googleblog.com/2016/08/flash-and-chrome.html from google's announcement.
