### ISSUE TITLE
Lost Query String

### ISSUE THREAD

**Issue by toddaa** [videojs/video-js-swf#217]
Query string variables in the media src seem to be lost when using the swf.  Is there any way to get them to pass to the server when the NetStream is initialized and told to play.  This seems to be fine when using HLS.

rtmp://server.example.com/app/file?var1=a&var2=b

Note: I have been appending query string variables to my source URLs which do absolutely nothing except add references to the servers log so that when I check the logs I can have some additional filtration methods.  My project is new to videojs.

**Comment by gkatsev** [comment]
Since video.js needs the url and stream name parts separated by the `&`, I think you want to add the query params to the url part. See the FAQ: https://github.com/videojs/video.js/blob/master/docs/guides/faq.md#q-how-can-i-play-rtmp-video-in-videojs
