### ISSUE TITLE
trying to play .swf file with video js

### ISSUE THREAD

**Issue by singhalsurbhi07** [videojs/video-js-swf#220]
I am trying to play a .swf file with video.js and I am getting message that either the network or server failed or format not supported. I know that video.js doesnot support .swf format but is it not possible to play .swf file with videojs with video-js-swf?
Thanks

**Comment by gkatsev** [comment]
video-js-swf is designed to play back flv and mp4 files as part of videojs/videojs-flash. It is not designed for loading and playing back other swf files.
