### ISSUE TITLE
`FCsubscribe` call breaks stream authentication

### ISSUE THREAD

**Issue by paluh** [videojs/video-js-swf#223]
I'm not sure why, but the latest change which adds `_nc.call("FCSubscribe", null, _src.streamURL)` breaks my authentication flow based on wowza secure token (it is based on query string parameters attached to `streamName`). I'm not sure if wowza can accept any `_nc` call before authenticating connection (which is done when stream connects - I'm not an RTMP expert) - it doesn't log anything interesting. I'm not familiar with ActionScript programming (but I'm to compile this project now ;-)) but I can add some config value to make this call optional. Could you suggest where should I put such an option and how to access this option from `RtmpVideoProvider`?

**Comment by albertogasparin** [comment]
That's interesting. I'm streaming from Facebook servers with a secure token (query string param too) and it is working fine 🤔

**Comment by gkatsev** [comment]
Facebook streams require the FSubscribe call and was one of the reasons we added it. I thought that it shouldn't be a problem. Making this optional (default is to call) sounds good.

Probably adding a flashVar for this is what you'd want. Take a look at https://github.com/videojs/video-js-swf/pull/207 for an example of flashvars usage.
