### ISSUE TITLE
how about on android and IOS ?

### ISSUE THREAD

**Issue by szhansen** [videojs/video-js-swf#224]
hi, anybody have a try on  IOS/ android  RTMP live  ?

or IOS HLS ?how about the video delay ? live video ?

**Comment by gkatsev** [comment]
RTMP and Flash do not work on mobile devices.
For live streams, your best bet is HLS, all mobile devices support it natively and you can even play it back on desktops using [videojs-contrib-hls](https://github.com/videojs/videojs-contrib-hls).

Hope that helps.
