### ISSUE TITLE
[bug]currentTime is not correct

### ISSUE THREAD

**Issue by victoryboss** [videojs/video-js-swf#235]
when flash player playing，I use `player.currentTime(13)`. 
It seems to seek to 13s, but the player seeks to 8s.
If the time is like 10/20/30/40，it seeks right

**Comment by gkatsev** [comment]
This generally has to do with the iframes/gops in the video. Flash can only seek to iframes so, if the closest iframe before second 13 is at 8s, it will seek to 8s.
Unfortunately, there's not much we can do on our end to fix this and it generally requires re-encoding the video to fix this.

**Comment by victoryboss** [comment]
Thank you .

**Comment by victoryboss** [comment]
This link explains what is gops
https://en.wikipedia.org/wiki/Group_of_pictures

**Comment by victoryboss** [comment]
Thank you very much！

**Comment by gkatsev** [comment]
you're welcome.
