### ISSUE TITLE
video-js-swf is not working in Microsoft Edge

### ISSUE THREAD

**Issue by klouskingsley** [videojs/video-js-swf#239]
## Step to reproduce:

- clone the repo
- grunt connect
- open "http://localhost:8000/tests/manual/manual.html" in Microsoft Edge

**Comment by gkatsev** [comment]
Flash is restricted on a lot of modern browsers nowadays. They often require you to enable or force a page to load in flash.
@OshinKaramian since you touched that folder last, does that page still work properly?
