### ISSUE TITLE
take snapShot not support ?

### ISSUE THREAD

**Issue by Qquanwei** [videojs/video-js-swf#240]
Is have a plan ?

**Comment by gkatsev** [comment]
We do not currently have plans to support taking screen captures from the swf.

**Comment by xpcode** [comment]
> We do not currently have plans to support taking screen captures from the swf.

please support

**Comment by Qquanwei** [comment]
@xpcode  This snippet for takeSnapshot .  @gkatsev  Should I submit a new PR for this ?

```actionscript
		private function onSnapShot(): *{
			var bitmapData:BitmapData = new BitmapData(stage.width, stage.height);
			bitmapData.draw(stage, new Matrix());
			
			var ba = PNGEncoder.encode(bitmapData);
			return "data:image/png;base64," + Base64.encode(ba);
		}
```

**Comment by xpcode** [comment]
> @xpcode This snippet for takeSnapshot . @gkatsev Should I submit a new PR for this ?
> 
> ```actionscript-3
> 		private function onSnapShot(): *{
> 			var bitmapData:BitmapData = new BitmapData(stage.width, stage.height);
> 			bitmapData.draw(stage, new Matrix());
> 			
> 			var ba = PNGEncoder.encode(bitmapData);
> 			return "data:image/png;base64," + Base64.encode(ba);
> 		}
> ```

very very thk u    @Qquanwei

**Comment by gkatsev** [comment]
Thanks for the snippet, however, I don't think we'll be adding features to the swf any time soon.
