### ISSUE TITLE
Can you change playbackRate?

### ISSUE THREAD

**Issue by gaxunil** [videojs/video-js-swf#242]
We are still supporting videojs on Win 7 IE 11. 
We have videojs 7 with videojs-flash and videojs-flash and videojs-flashls-source-handler.

Calling player.playbackRate(2) on the player results in errors saying that there is no such property for Flash.

videojs-flash seems to indicate that there may be a setPlaybackRate() function, but I'm still fuzzy if that is correct.

Should this work?
Is there a playbackRate(rate) or setPlaybackRate(rate) setter available for Flash in this way?
Thanks

**Comment by gkatsev** [comment]
Unfortunately, we do not support changing the playbackrate with the flash tech and the swf. I'm not sure that Flash has support for different playback rates for us to use.
