### ISSUE TITLE
currentTime always stays on zero after changing tech

### ISSUE THREAD

**Issue by ahmadazimi** [videojs/video-js-swf#62]
After changing player source from html5 to flash, currentTime passed by SWF always stays zero.

**Comment by ahmadazimi** [comment]
There is no update available?

**Comment by Yugloocamai** [comment]
currentTime = x is definitely broken in my Chrome.

**Comment by ZorionTen** [comment]
yep..still not working .. modifying currentTime resets it to 0

Chrome Version 85.0.4183.121 (Official Build) (64-bit)
ubuntu 20

**Comment by gkatsev** [comment]
Due to Flash being end of lifed at the end of the year and how hard browsers make it to run flash right now, it's very unlikely that we'll spend time investigating and fixing it.
If a PR with a fix is made, we'll consider merging the fix but even that is definitely low priority for us.
