### ISSUE TITLE
Can't switch from HTTP to RTMP playback

### ISSUE THREAD

**Issue by heff** [videojs/video-js-swf#92]
In videojs/video.js#834 it's been confirmed that when you switch from an mp4 (playing in flash) to an RTMP stream, you get an unknown TypeError. This doesn't happen when switching between other formats, so it seems to be something internal to the flash player that can't handle switching to an RTMP source after already loading HTTP playback.

RTC: http://jsfiddle.net/R7dmf/

See videojs/video.js#834 for more information.

**Comment by khurram25** [comment]
@heff any chance of this issue getting fixed in vjs5. can you recommend any videojs-resolution-selector plugin which worked for rtmp.
i found another plugin at https://github.com/kmoskwiak/videojs-resolution-switcher but this also seems to be broken for rtmp/mp4
